export default {
  listingAgent: {
    Name: '',
    Phone: '',
    Email: '',
  },
  status: '',
  date: new Date().toISOString(),
  location: {
    Address: '',
    City: '',
    State: '',
    ZIP: '',
  },
  listPrice: '',
  'MLS URL': '',
  'Rent Details': {
    'Total Rent': '',
    'Beds Unit 1': '',
    'Baths Unit 1': '',
    'Sq Ft Unit 1': '',
    'Unit 1 Current Rent Rate': '',
    'Rent Potential': '',
    'Beds Unit 2': '',
    'Baths Unit 2': '',
    'Sq Ft Unit 2': '',
    'Unit 2 Current Rent Rate': '',
    'Rent Potential 2': '',
  },
  'LOI Status': '',
  Notes: {
    Buyer: '',
    Moudy: '',
    Contractor: '',
    Agent: '',
  },
  'Estimated Rehab Cost': '',
  'Estimated ARV': '',
  Equity: '',
  BRRRR: {
    'LOI Cash Price': '',
    'MAX REFI AMOUNT': '',
    'CASH LEFT IN HOUSE': '',
    'CURRENT MONTHLY CASHFLOW': '',
    'ANNUAL COC RETURN CURRENT': '',
    'POTENTIAL MONTHLY CASHFLOW': '',
    'ANNUAL COC RETURN POTENTIAL': '',
  },
  'Conventional Financing': {
    'LOI Conventional': '',
    'DOWN PAYMENT': '',
    'MORTGAGE AMOUNT': '',
    'CASH IN HOUSE': '',
    'MONTHLY CASHFLOW': '',
    'COC RETURN CURRENT': '',
    'MONTHLY CASHFLOW POTENTIAL': '',
    'COC RETURN POTENTIAL': '',
  },
  'Seller Financing': {
    'LOI SELLER FINANCING': '',
    'DOWN PAYMENT': '',
    'MORTGAGE AMOUNT': '',
    'CASH IN HOUSE': '',
    'MONTHLY CASHFLOW': '',
    'COC RETURN CURRENT': '',
    'MONTHLY CASHFLOW POTENTIAL': '',
    'COC RETURN POTENTIAL': '',
  },
};

// export default {
//   name: '',
//   address: '',
//   amount: 0,
//   date: new Date().toISOString(),
// };